// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgmyxbesvlamfvjsdzly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbXl4YmVzdmxhbWZ2anNkemx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTcyOTMsImV4cCI6MjA3MTQzMzI5M30.L1JCAva0t6R3oHLhYpYrl9LEq6hAo_-Kux5lrAK9Y5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});