// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edobyxrhmqnyyxqqiqcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkb2J5eHJobXFueXl4cXFpcWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDA2MjAsImV4cCI6MjA3NDExNjYyMH0.3UormDhpotjrw0qUDt0dhUjqf1T1LTtg1V_HiqhcDdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});